[package]
name = "crisol-gc"
description = "Precise mark-sweep collector, shadow stack, rooting."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
crisol-value.workspace = true
