[package]
name = "crisol-frontend"
description = "oxc wrapper, module resolution, module graph."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
crisol-ir.workspace = true
crisol-value.workspace = true
oxc_allocator.workspace = true
oxc_ast.workspace = true
oxc_ast_visit.workspace = true
oxc_parser.workspace = true
oxc_resolver.workspace = true
oxc_span.workspace = true
