[package]
name = "crisol-html"
description = "html5ever integration: HTML source to node tree."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
crisol-tree.workspace = true
html5ever.workspace = true
thiserror.workspace = true

[dev-dependencies]
crisol-css.workspace = true
crisol-display-list.workspace = true
crisol-layout.workspace = true
crisol-style.workspace = true
