[package]
name = "crisol-css"
description = "lightningcss parsing and `selectors` matching."
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
crisol-display-list.workspace = true
crisol-tree.workspace = true
cssparser.workspace = true
lightningcss.workspace = true
precomputed-hash.workspace = true
selectors.workspace = true
smallvec.workspace = true
static-self.workspace = true
thiserror.workspace = true

[dev-dependencies]
lightningcss.workspace = true
